export type BlogPost = {
  title: string;
  href: string;
  date: string;
  dateLabel: string;
  image: string;
};

export const blogPosts: BlogPost[] = [
  {
    title: "Can You Put Neosporin on a Dog? What You Need to Know",
    href: "/about/blog/can-you-put-neosporin-on-a-dog",
    date: "2025-02-27",
    dateLabel: "February 27, 2025",
    image: "/images/blog/olive-and-louie.jpg",
  },
  {
    title: "How to Stop a Dog from Barking: A Guide to Sanity",
    href: "/about/blog/how-to-stop-a-dog-from-barking",
    date: "2025-02-20",
    dateLabel: "February 20, 2025",
    image: "/images/blog/olive-barking.jpg",
  },
  {
    title: "How to Get Rid of Skunk Smell on Your Dog",
    href: "/about/blog/how-to-get-rid-of-skunk-smell",
    date: "2025-02-13",
    dateLabel: "February 13, 2025",
    image: "/images/blog/olive-bath.jpg",
  },
  {
    title: "Why Are Dogs' Noses Wet? The Cool, Sniff-Tastic Truth",
    href: "https://pooptopia.dog/woof-to-waste-blog/f/why-are-dogs-noses-wet-the-cool-sniff-tastic-truth",
    date: "2025-02-06",
    dateLabel: "February 6, 2025",
    image: "/images/gallery/grass-closeup.webp",
  },
  {
    title: "5 Indoor Activities to Keep Your Dog Active During Winter",
    href: "https://pooptopia.dog/woof-to-waste-blog/f/5-indoor-activities-to-keep-your-dog-active-during-winter",
    date: "2025-01-30",
    dateLabel: "January 30, 2025",
    image: "/images/gallery/dogs-in-yard.webp",
  },
  {
    title: "The Secret Language of Dog Poop: What It Reveals About Your Dog",
    href: "https://pooptopia.dog/woof-to-waste-blog/f/the-secret-language-of-dog-poop-what-it-reveals-about-your-dog",
    date: "2025-01-28",
    dateLabel: "January 28, 2025",
    image: "/images/gallery/before-after-snow-corner.webp",
  },
  {
    title: "The Hidden Dangers of Dog Poop in Winter",
    href: "https://pooptopia.dog/woof-to-waste-blog/f/the-hidden-dangers-of-dog-poop-in-winter",
    date: "2025-01-23",
    dateLabel: "January 23, 2025",
    image: "/images/gallery/waste-bags-snow.webp",
  },
  {
    title: "Why a Poop-Free Lawn Matters Year-Round",
    href: "https://pooptopia.dog/woof-to-waste-blog/f/why-a-poop-free-lawn-matters-year-round",
    date: "2025-01-21",
    dateLabel: "January 21, 2025",
    image: "/images/sanitizing.webp",
  },
  {
    title: "Top Winter Dog Toys for 2025: Keeping Your Pup Active and Engaged",
    href: "https://pooptopia.dog/woof-to-waste-blog/f/top-winter-dog-toys-for-2025-keeping-your-pup-active-and-engaged",
    date: "2025-01-16",
    dateLabel: "January 16, 2025",
    image: "/images/gallery/before-after-tree.webp",
  },
  {
    title: "Protecting Your Dog’s Paws in Winter: Tips for Happy/Healthy Feet",
    href: "https://pooptopia.dog/woof-to-waste-blog/f/protecting-your-dog%E2%80%99s-paws-in-winter-tips-for-happyhealthy-feet",
    date: "2025-01-14",
    dateLabel: "January 14, 2025",
    image: "/images/gallery/before-after-planter.webp",
  },
  {
    title: "Why Dogs Eat Poop: The Smelly Truth We Can’t Ignore",
    href: "https://pooptopia.dog/woof-to-waste-blog/f/why-dogs-eat-poop-the-smelly-truth-we-can%E2%80%99t-ignore",
    date: "2025-01-11",
    dateLabel: "January 11, 2025",
    image: "/images/gallery/before-after-slope.webp",
  },
  {
    title: "Why Do Dogs Walk and Poop? Unpacking Canine Bathroom Behavior",
    href: "https://pooptopia.dog/woof-to-waste-blog/f/why-do-dogs-walk-and-poop-unpacking-canine-bathroom-behavior",
    date: "2025-01-09",
    dateLabel: "January 9, 2025",
    image: "/images/gallery/before-after-fence.webp",
  },
  {
    title: "Winter Yard Tips: Keeping Your Dog Safe and Comfortable",
    href: "https://pooptopia.dog/woof-to-waste-blog/f/winter-yard-tips-keeping-your-dog-safe-and-comfortable",
    date: "2025-01-07",
    dateLabel: "January 7, 2025",
    image: "/images/gallery/before-after-gravel.webp",
  },
  {
    title: "New Year, New Yard: Setting Up Dog-Friendly Outdoor Resolutions",
    href: "https://pooptopia.dog/woof-to-waste-blog/f/new-year-new-yard-setting-up-dog-friendly-outdoor-resolutions",
    date: "2025-01-02",
    dateLabel: "January 2, 2025",
    image: "/images/gallery/before-after-trampoline.webp",
  },
  {
    title: "Year in Review: Celebrating Your Dog’s Wins in 2024",
    href: "https://pooptopia.dog/woof-to-waste-blog/f/year-in-review-celebrating-your-dog%E2%80%99s-wins-in-2024",
    date: "2024-12-31",
    dateLabel: "December 31, 2024",
    image: "/images/gallery/team-rakes.webp",
  },
  {
    title: "New Year’s Resolutions: Health Goals for Dogs in 2025",
    href: "https://pooptopia.dog/woof-to-waste-blog/f/new-year%E2%80%99s-resolutions-health-goals-for-dogs-in-2025",
    date: "2024-12-26",
    dateLabel: "December 26, 2024",
    image: "/images/gallery/team-curbside.webp",
  },
  {
    title: "Frosty Frolics: Safe Winter Fun with Your Dog",
    href: "https://pooptopia.dog/woof-to-waste-blog/f/frosty-frolics-safe-winter-fun-with-your-dog",
    date: "2024-12-24",
    dateLabel: "December 24, 2024",
    image: "/images/newsletter-yard.webp",
  },
  {
    title: "Traveling Tails: Holiday Tips for Trips with Your Dog",
    href: "https://pooptopia.dog/woof-to-waste-blog/f/traveling-tails-holiday-tips-for-trips-with-your-dog",
    date: "2024-12-19",
    dateLabel: "December 19, 2024",
    image: "/images/hero-yard-planter.webp",
  },
  {
    title: "Winter Weight Management: Adjusting Your Dog’s Diet and Exercise",
    href: "https://pooptopia.dog/woof-to-waste-blog/f/winter-weight-management-adjusting-your-dog%E2%80%99s-diet-and-exercise",
    date: "2024-12-17",
    dateLabel: "December 17, 2024",
    image: "/images/gallery/late-winter-yard.webp",
  },
  {
    title: "Holiday Hazards: Keeping Your Dog Safe from Foods and Decorations",
    href: "https://pooptopia.dog/woof-to-waste-blog/f/holiday-hazards-keeping-your-dog-safe-from-foods-and-decorations",
    date: "2024-12-12",
    dateLabel: "December 12, 2024",
    image: "/images/gallery/before-after-wide-yard.webp",
  },
  {
    title: "Indoor Adventures: Keep Your Dog Mentally Stimulated In Winter",
    href: "https://pooptopia.dog/woof-to-waste-blog/f/indoor-adventures-keep-your-dog-mentally-stimulated-in-winter",
    date: "2024-12-10",
    dateLabel: "December 10, 2024",
    image: "/images/clean-yard.webp",
  },
  {
    title: "Cozy Canines: Choosing the Right Winter Gear for Your Dog",
    href: "https://pooptopia.dog/woof-to-waste-blog/f/cozy-canines-choosing-the-right-winter-gear-for-your-dog",
    date: "2024-12-05",
    dateLabel: "December 5, 2024",
    image: "/images/gallery/grass-closeup.webp",
  },
  {
    title: "Paw-dicure 101: Protecting Your Dog's Paws from Winter's Wrath",
    href: "https://pooptopia.dog/woof-to-waste-blog/f/paw-dicure-101-protecting-your-dogs-paws-from-winters-wrath",
    date: "2024-12-03",
    dateLabel: "December 3, 2024",
    image: "/images/gallery/dogs-in-yard.webp",
  },
  {
    title: "Why Does My Dog Sleep on His Back?",
    href: "https://pooptopia.dog/woof-to-waste-blog/f/why-does-my-dog-sleep-on-his-back",
    date: "2024-11-28",
    dateLabel: "November 28, 2024",
    image: "/images/gallery/before-after-snow-corner.webp",
  },
  {
    title: "Thanksgiving Pet Safety: How to Keep Your Pets Safe",
    href: "https://pooptopia.dog/woof-to-waste-blog/f/thanksgiving-pet-safety-how-to-keep-your-pets-safe",
    date: "2024-11-26",
    dateLabel: "November 26, 2024",
    image: "/images/gallery/waste-bags-snow.webp",
  },
  {
    title: "Antifreeze Poisoning in Dogs: How to Keep Your Pet Safe",
    href: "https://pooptopia.dog/woof-to-waste-blog/f/antifreeze-poisoning-in-dogs-how-to-keep-your-pet-safe",
    date: "2024-11-21",
    dateLabel: "November 21, 2024",
    image: "/images/sanitizing.webp",
  },
  {
    title: "Why Do Dogs Lick Their Paws?",
    href: "https://pooptopia.dog/woof-to-waste-blog/f/why-do-dogs-lick-their-paws",
    date: "2024-11-19",
    dateLabel: "November 19, 2024",
    image: "/images/gallery/before-after-tree.webp",
  },
  {
    title: "Can Dogs See TV? Understanding How Dogs Perceive Television",
    href: "https://pooptopia.dog/woof-to-waste-blog/f/can-dogs-see-tv-understanding-how-dogs-perceive-television",
    date: "2024-11-14",
    dateLabel: "November 14, 2024",
    image: "/images/gallery/before-after-planter.webp",
  },
  {
    title: "Understanding Reverse Sneezing in Dogs",
    href: "https://pooptopia.dog/woof-to-waste-blog/f/understanding-reverse-sneezing-in-dogs",
    date: "2024-11-12",
    dateLabel: "November 12, 2024",
    image: "/images/gallery/before-after-slope.webp",
  },
  {
    title: "Why You Should Rake Up Those Fall Leaves (For Your Yard and Dog)",
    href: "https://pooptopia.dog/woof-to-waste-blog/f/why-you-should-rake-up-those-fall-leaves-for-your-yard-and-dog",
    date: "2024-11-09",
    dateLabel: "November 9, 2024",
    image: "/images/gallery/before-after-fence.webp",
  },
  {
    title: "Caring for Your Dog's Paws, Coat, and Nose in the Winter",
    href: "https://pooptopia.dog/woof-to-waste-blog/f/caring-for-your-dogs-paws-coat-and-nose-in-the-winter",
    date: "2024-11-06",
    dateLabel: "November 6, 2024",
    image: "/images/gallery/before-after-gravel.webp",
  },
  {
    title: "Why Do Dogs Sigh?",
    href: "https://pooptopia.dog/woof-to-waste-blog/f/why-do-dogs-sigh",
    date: "2024-11-06",
    dateLabel: "November 6, 2024",
    image: "/images/gallery/before-after-trampoline.webp",
  },
  {
    title: "Why Do My Dog’s Feet Smell Like Fritos?",
    href: "https://pooptopia.dog/woof-to-waste-blog/f/why-do-my-dog%E2%80%99s-feet-smell-like-fritos",
    date: "2024-10-31",
    dateLabel: "October 31, 2024",
    image: "/images/gallery/team-rakes.webp",
  },
  {
    title: "DIY Cognitive Dog Toys for Home: How to Stimulate Your Dog’s Mind",
    href: "https://pooptopia.dog/woof-to-waste-blog/f/diy-cognitive-dog-toys-for-home-how-to-stimulate-your-dog%E2%80%99s-mind",
    date: "2024-10-29",
    dateLabel: "October 29, 2024",
    image: "/images/gallery/team-curbside.webp",
  },
  {
    title: "Halloween Pet Safety: Keeping Your Pets Safe and Happy",
    href: "https://pooptopia.dog/woof-to-waste-blog/f/halloween-pet-safety-keeping-your-pets-safe-and-happy",
    date: "2024-10-24",
    dateLabel: "October 24, 2024",
    image: "/images/newsletter-yard.webp",
  },
  {
    title: "Hidden Household Hazards: Common Items That Are Dangerous to Dogs",
    href: "https://pooptopia.dog/woof-to-waste-blog/f/hidden-household-hazards-common-items-that-are-dangerous-to-dogs",
    date: "2024-10-22",
    dateLabel: "October 22, 2024",
    image: "/images/hero-yard-planter.webp",
  },
  {
    title: "Dog Diarrhea: Causes, Treatments, and When to See a Vet",
    href: "https://pooptopia.dog/woof-to-waste-blog/f/dog-diarrhea-causes-treatments-and-when-to-see-a-vet",
    date: "2024-10-17",
    dateLabel: "October 17, 2024",
    image: "/images/gallery/late-winter-yard.webp",
  },
  {
    title: "Why Is My Old Dog Whining for No Apparent Reason?",
    href: "https://pooptopia.dog/woof-to-waste-blog/f/why-is-my-old-dog-whining-for-no-apparent-reason",
    date: "2024-10-15",
    dateLabel: "October 15, 2024",
    image: "/images/gallery/before-after-wide-yard.webp",
  },
  {
    title: "Why Is My Dog Pooping Blood? Common Causes and What to Do",
    href: "https://pooptopia.dog/woof-to-waste-blog/f/why-is-my-dog-pooping-blood-common-causes-and-what-to-do",
    date: "2024-10-10",
    dateLabel: "October 10, 2024",
    image: "/images/clean-yard.webp",
  },
  {
    title: "Dog Boarding Tips: How to Prepare for a Stay Away from Home",
    href: "https://pooptopia.dog/woof-to-waste-blog/f/dog-boarding-tips-how-to-prepare-for-a-stay-away-from-home",
    date: "2024-10-08",
    dateLabel: "October 8, 2024",
    image: "/images/gallery/grass-closeup.webp",
  },
  {
    title: "Loving Your Dog: Building a Stronger Bond with Your Companion",
    href: "https://pooptopia.dog/woof-to-waste-blog/f/loving-your-dog-building-a-stronger-bond-with-your-companion",
    date: "2024-10-03",
    dateLabel: "October 3, 2024",
    image: "/images/gallery/dogs-in-yard.webp",
  },
  {
    title: "Fun and Effective Ways to Stay Active with Your Dog",
    href: "https://pooptopia.dog/woof-to-waste-blog/f/fun-and-effective-ways-to-stay-active-with-your-dog",
    date: "2024-10-01",
    dateLabel: "October 1, 2024",
    image: "/images/gallery/before-after-snow-corner.webp",
  },
  {
    title: "Managing Fall Allergies in Dogs: Tips for Pet Owners",
    href: "https://pooptopia.dog/woof-to-waste-blog/f/managing-fall-allergies-in-dogs-tips-for-pet-owners",
    date: "2024-09-26",
    dateLabel: "September 26, 2024",
    image: "/images/gallery/waste-bags-snow.webp",
  },
  {
    title: "Why Cleaning Up Dog Poop in Your Yard is Crucial During Winter",
    href: "https://pooptopia.dog/woof-to-waste-blog/f/why-cleaning-up-dog-poop-in-your-yard-is-crucial-during-winter",
    date: "2024-09-24",
    dateLabel: "September 24, 2024",
    image: "/images/sanitizing.webp",
  },
  {
    title: "Is Dog Poop Compostable? Understanding Composting for Pet Waste",
    href: "https://pooptopia.dog/woof-to-waste-blog/f/is-dog-poop-compostable-understanding-composting-for-pet-waste",
    date: "2024-09-19",
    dateLabel: "September 19, 2024",
    image: "/images/gallery/before-after-tree.webp",
  },
  {
    title: "How Daylight Savings Time Affects Your Dog: What You Need to Know",
    href: "https://pooptopia.dog/woof-to-waste-blog/f/how-daylight-savings-time-affects-your-dog-what-you-need-to-know",
    date: "2024-09-17",
    dateLabel: "September 17, 2024",
    image: "/images/gallery/before-after-planter.webp",
  },
  {
    title: "Understanding and Managing Dog Constipation: Tips for Pet Owners",
    href: "https://pooptopia.dog/woof-to-waste-blog/f/understanding-and-managing-dog-constipation-tips-for-pet-owners",
    date: "2024-09-12",
    dateLabel: "September 12, 2024",
    image: "/images/gallery/before-after-slope.webp",
  },
  {
    title: "Why Do Dogs Eat Dirt?",
    href: "https://pooptopia.dog/woof-to-waste-blog/f/why-do-dogs-eat-dirt",
    date: "2024-09-10",
    dateLabel: "September 10, 2024",
    image: "/images/gallery/before-after-fence.webp",
  },
  {
    title: "Can Dogs Get Colds? Understanding Canine Respiratory Health",
    href: "https://pooptopia.dog/woof-to-waste-blog/f/can-dogs-get-colds-understanding-canine-respiratory-health",
    date: "2024-09-05",
    dateLabel: "September 5, 2024",
    image: "/images/gallery/before-after-gravel.webp",
  },
  {
    title: "Fall Safety Tips for Pets",
    href: "https://pooptopia.dog/woof-to-waste-blog/f/fall-safety-tips-for-pets",
    date: "2024-09-03",
    dateLabel: "September 3, 2024",
    image: "/images/gallery/before-after-trampoline.webp",
  },
];
